### ISSUE TITLE
How do I find the 3.2 documentation these days?

### ISSUE THREAD

**Issue by bar10dr** [coreui/coreui-website#18]
When I go to the main site (https://coreui.io/vue/)

Hover over Docs in the header, then click Documentation for 3.2, it takes me to the 4.0 documentation.

How do I get to the old 3.2 documentation?

**Comment by mrholek** [comment]
Hi, I fixed it, 3.2 is available on our website. You can also use this direct link https://coreui.io/vue/docs/3.2/introduction/
